### ISSUE TITLE
Vue component's symbol is incorrect

### ISSUE THREAD

**Issue by ChangJoo-Park** [wallabyjs/wallaby-vue-compiler#1]
![2017-07-18 10 24 50](https://user-images.githubusercontent.com/1451365/28319166-185178f2-6c08-11e7-84a7-ad3c6b5d092c.png)

I add some test code using Vue component's propsData.
Testing was well, but wallaby symbol in Component code.
please see this [commit](https://github.com/ChangJoo-Park/vue-wallaby-webpack-template/commit/9795827396aead7836bc837a6f0d8c6fd9570b30)

**Comment by ArtemGovorov** [comment]
I may be missing something, but everything on the screenshot looks correct to me. Could you please describe what exactly is incorrect?

**Comment by ChangJoo-Park** [comment]
`count` is not data, It is props. Wallaby's green(or red) symbol is not exact place in Hello.vue component. 

It does not matter if it's what you intended. It just my curious. 

Other things are working awesome! 👍  
This is `Hello.spec.js`  includes another data, methods, computed property 

https://github.com/ChangJoo-Park/vue-wallaby-webpack-template/blob/master/test/unit/specs/Hello.spec.js

**Comment by ArtemGovorov** [comment]
@ChangJoo-Park Thanks for the update. I have checked the code and looks like everything is working as intended.

> `count` is not data, It is props. Wallaby's green(or red) symbol is not exact place in Hello.vue component.

I'm still not sure what you mean. Wallaby.js code coverage indicators are displayed only for code regions that can be both: executed or not executed. For example:

![screen shot 2017-07-19 at 11 41 46 am](https://user-images.githubusercontent.com/979966/28346908-4b120b16-6c77-11e7-8cf8-644bfafe54e7.png)

the 
```javascript
return this.msg.split('').reverse().join('')
``` 
statement, the 

```javascript
return {
      msg: 'Welcome to Your Vue.js App',
      itemCount: 0
    }
``` 
statement, and the 
```javascript
 this.itemCount++
```

can be executed or not executed. They are executed from tests, so they are green.

This part however:

```javascript
  ...
  name: 'hello',
  props: {
    count: {
      type: Number,
      default: 1
    }
  },
```
is just a part of the exported object declaration and it is always executed, so no indicators are displayed. If there were some logical branches in the definition (that can be executed or not executed), for example an `||` operator, then the indicator would be displayed:

![screen shot 2017-07-19 at 11 54 11 am](https://user-images.githubusercontent.com/979966/28347216-1664ec2e-6c79-11e7-97c3-2d175c87b601.png)

Hope it makes sense. If it's not what you meant, or I'm missing something, please let me know.

**Comment by ChangJoo-Park** [comment]
I was confused before you expalin. 

![](https://user-images.githubusercontent.com/979966/28347216-1664ec2e-6c79-11e7-97c3-2d175c87b601.png) 
this screenshot is what I expect and I misunderstood meaning of green symbol 😢 

Now I am understand clearly 👍 

Thanks @ArtemGovorov
